### PR TITLE
Test also OCaml 4.07, 4.08, 4.09

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by XVilka** [comment]
Everything seems fine, except `dkcheck` version check, not sure where it's done:
```
Asking 'dkcheck' for its version number.
Program 'dkcheck' has version '2.6.0'.
ERROR: version constraint not satisfied: v2.5 <= 2.6.0
ERROR: version constraint not satisfied: 2.6.0 = devel
```

**Comment by XVilka** [comment]
Ok, totally green now, feel free to squash and merge.

**Comment by XVilka** [comment]
Please don't forget about this one.

**Comment by XVilka** [comment]
Ping?

**Comment by GuillaumeGen** [comment]
We finally merged it. Thanks @XVilka

**Pull request merged**
